### ISSUE TITLE
Add support for ~/.gemrc proxy

### ISSUE THREAD

**Issue by athityakumar** [athityakumar/proxyrc#1]

**Comment by kaustubhhiware** [comment]
Hey, I was planning to write a similar script, so I realised npm also uses a proxy.

You could consider adding it as well.

**Comment by athityakumar** [comment]
@kaustubhhiware - Haven't really used much of npm. A simple search says that `npm config set (proxy|https-proxy) http://...` will set the proxy, but how to unset?

**Comment by kaustubhhiware** [comment]
`npm config unset proxy` or something similar.

If it's okay with you, I can add support for both gemrc and npmrc and send a PR

**Comment by athityakumar** [comment]
Of course, sure. 😄

**Comment by athityakumar** [comment]
Done with PR #3
