### ISSUE TITLE
Configuration for fish mentioned incorrectly

### ISSUE THREAD

**Issue by kaustubhhiware** [athityakumar/proxyrc#2]
> Add this to your shell configuration file (~/.bashrc, .zshrc or .fishrc) -

Fish doesn't have a fishrc.  It has a config.fish

In order to define a function, a separate function.fish file must be written.
If it's fine with you, I'll write the function file and add it to the repo, so the usage in fish would be download another file with curl, then you're ready to go.

**Comment by athityakumar** [comment]
Added by PR #4
